# Generated by Django 3.0.2 on 2023-01-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
